
on: [push]

env:
  AZURE_WEBAPP_NAME: StaticHtmlAppSrvGH

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
    - name: 'Create Artifact'
      uses: montudor/action-zip@v0.1.1
      with:
<<<<<<< HEAD
        args: zip -qq -r artifact.zip . -x 'README.md' -x '.github' -x '.git'
=======
        args: zip -qq -r artifact.zip ./src
>>>>>>> b262b805a8bb6eac17d48e9d17e0a751d1cf88d4
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifact.zip  
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: artifact.zip
