name: Workflow to run manually

on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: StaticHtmlAppSrvGH

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    #- name: 'Bash script test'
    #  run: |
    #    rm asdfasfasdfdasdfaf
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2
    - name: 'Create Artifact'
      uses: montudor/action-zip@v0.1.1
      with:
        args: zip -r -j artifact.zip src
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifact.zip  
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: artifact.zip
